#
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
     app: my-cloth-service 
spec:
  containers:
      
    - name: apache2-app
      image: apache2
      ports:
       - containerPort: 80

    - name: java-app
      image: tomcat:latest
      ports:
       - containerPort: 8080

    - name: mysql-app
      image: tomcat:latest
      ports:
       - containerPort: 3306
    
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: "redhat"