apiVersion: v1
kind: ReplicationController
metadata:
    name: my-rc
    labels:
      app: my-app
spec:
  template:
    metadata:
      name: my-rc
      labels:
         app: my-app

    spec:
      containers:
        - name: nginx-app
          image: nginx
          ports:
            containerPort: 80

  replicas: 3
  selector:
    app: my-app

