apiVersion: v1
kind: Service
metadata: 
  name: cloth-service
  labels:
    app: cloth-app
spec:
  ports:
   - targetPort: 3306
     port: 3306
     protocol: TCP
     name: http

  selector:
    app: my-cloth-service
  type: NodePort

